---
- name: "Create Code Repo for the Archeplay Template"
  hosts: localhost
  become: true
  tasks:
  - block:
      - set_fact:
          code: "{{ lookup('vars', 'code')}}"
          apiname: "{{ lookup('vars', 'apiname')}}"
          AppType: "{{ lookup('vars', 'AppType')}}"
          apidefinition: "{{ lookup('vars', 'apidefinition')}}"
          db: "{{ lookup('vars', 'db')}}"
      - name: Execute Step
        include_role:
          name: executestep
        vars:
          stepname: codecommitbackup
          stepdesc: Backup the Code Commit Repo and push to Templaterepo
          stepno: 1
          stepaction: delete
        when: code.CodeRepoType == "codecommit"
      - name: Execute Step
        include_role:
          name: executestep
        vars:
          stepname: codecommit
          stepdesc: Delete the code Commit
          stepno: 2
          stepaction: delete
        when: code.CodeRepoType == "codecommit"
      - name: get env status
        include_role:
          name: stepop
        vars:
          envstatus: Deleted
    rescue:
      - name: get env status
        include_role:
          name: stepop
        vars:
          envstatus: Failed