- name: Step {{stepno}} - {{stepname}} - Task 1 - dynamodb -  Create Secondary Key in DynamoDB Table
  include_tasks:
    file: seckey.yaml
  loop:
    "{{table.secondarykeys}}"
  loop_control:
    loop_var: secondarykey
  register: secondarykeycreate