---
- name: "Create Code Repo for the Archeplay Template"
  hosts: localhost
  become: true
  tasks:
  - block:
      - name: Execute Step
        include_role:
          name: executestep
        vars:
          stepname: asg
          stepdesc: ECS Cluster Creation
          stepno: 1
          stepaction: create
      
      - name: Execute Step
        include_role:
          name: executestep
        vars:
          stepname: asg
          stepdesc: ECS Cluster describe
          stepno: 1
          stepaction: describe
          
      - name: get env status
        include_role:
          name: stepop
        vars:
          envstatus: Running
    
    rescue:
      - name: Execute rollback Step
        include_role:
          name: executestep
        vars:
          stepname: cluster
          stepdesc: rollback ecscluster
          stepno: 1
          stepaction: rollback
      
      - name: get env status
        include_role:
          name: stepop
        vars:
          envstatus: Failed