---
AWSTemplateFormatVersion: 2010-09-09
Description:  This template deploys VPC S3 Endpoint in public network.
Metadata:
  Architecture:
    - Title: s3endpoint
      Image: image1
      Description: Architecture for Vpc S3 Endpoint.

Parameters:
  VPCID:
    Description: This is a dependent parameter and will be taken from VPC environment.
    Type: String

  RouteTableId:
    Description: This is public route table id and will be taken from VPC environment.
    Type: String
  
Resources:
  VpcS3Endpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Metadata:
      Description: This resource will create a S3 endpoint in public network.
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:*'
            Resource:
              - '*'
      RouteTableIds:
        -
          Ref: RouteTableId
      ServiceName:
        'Fn::Sub': 'com.amazonaws.${AWS::Region}.s3'
      VpcId:
        Ref: VPCID

Outputs:
  S3EndPoint:
    Description: Vpc endpoint id for s3
    Value: !Ref VpcS3Endpoint
    Export: 
      Name: 
        Fn::Sub: "${AWS::StackName}-s3endpoint"