---
AWSTemplateFormatVersion: 2010-09-09
Description: Environment deploys a RDS MYSQL Database in private subnet and deletes the database when you delete the environment.
Metadata:
  Architecture{{deploymentid}}:
    - Title: single az
      Image: rdsmsingleaz
      Description: Architecture for Single AZ RDS.
    - Title: multi az
      Image: rdsmultiaz
      Description: Architecture for Multi AZ RDS.
      
Parameters:
  VPCID{{deploymentid}}:
    Description: VPC ID where you want to deploy the RDS. This will be taken from VPC environment.
    Type: String
    
  PrivateSubnet1ID{{deploymentid}}:
    Description: Private subnet id of 1st availability zone will be taken from the VPC environment for creating a subnet group for RDS.
    Type: String
  
  PrivateSubnet2ID{{deploymentid}}:
    Description: Private subnet id of 2nd availability zone will be taken from the VPC environment for creating a subnet group for RDS.
    Type: String

  DBName{{deploymentid}}:
    Default: mysqldb
    Description: Give the name of the database for your database instance.
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
  
  DBUsername{{deploymentid}}:
    NoEcho: true
    Description: Give username for RDS MySQL Database.
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
    Default: mysqldbuser
    
  DBPassword{{deploymentid}}:
    NoEcho: true
    Description: Password for your RDS MySQL Database will be autogenerated. 
    Type: String
    MinLength: '8'
    MaxLength: '41'
  
  EngineName{{deploymentid}}:
    Default: mysql
    Description: Select the engine type you want to deploy.
    Type: String
    AllowedValues:
      - mysql
  
  EngineVersion{{deploymentid}}:
    Default: 5.7.19
    Description: Choose an Engine Version for your engine.
    Type: String
    AllowedValues: [
      "5.7.16",
      "5.7.17",
      "5.7.19",
      "5.7.21",
      "5.7.22",
      "5.7.23",
      "5.7.24",
      "5.7.25",
      "5.7.26",
      "5.7.28",
      "5.7.30",
      "8.0.11",
      "8.0.13",
      "8.0.15",
      "8.0.16",
      "8.0.17",
      "8.0.19",
      "8.0.20"]
    
  DBInstanceClass{{deploymentid}}:
    Default: db.t2.micro
    Description: Select DB instance type for the Database Instance.
    Type: String
    ConstraintDescription: Must select a valid DB instance type.
    AllowedValues:
      - db.t2.micro
      - db.t2.small
      - db.t2.medium
      - db.t2.large
      - db.t2.xlarge
      - db.t2.2xlarge
      - db.m5.large
      - db.m5.xlarge
      - db.m5.2xlarge
      - db.m5.4xlarge
      - db.m5.12xlarge
      - db.m5.24xlarge
      - db.m4.large
      - db.m4.2xlarge
      - db.m4.4xlarge
      - db.m4.10xlarge
      - db.m4.16xlarge
      - db.m1.small
      - db.m1.medium
      - db.m1.large
      - db.m1.xlarge
      - db.m3.medium
      - db.m3.large
      - db.m3.xlarge
      - db.m3.2xlarge
      - db.r3.large
      - db.r3.xlarge
      - db.r3.2xlarge
      - db.r3.4xlarge
      - db.r3.8xlarge
      
  DBAllocatedStorage1{{deploymentid}}:
    Default: 50
    Description: Give the Storage size you want for your database instance if you want to use general purpose (gp2) storage type.
    Type: Number
    MinValue: 20
    MaxValue: 10000
    ConstraintDescription: must be between 20 and 10000 GiB.
  
  DBAllocatedStorage2{{deploymentid}}:
    Default: 200
    Description: Give the Storage size you want for your database instance if you want to use  provisioned IOPS SSD (io1) storage type.
    Type: Number
    MinValue: 200
    MaxValue: 10000
    ConstraintDescription: must be between 200 and 10000 GiB.
  
  Storagetype{{deploymentid}}:
    Default: gp2
    Type: String
    Description: Choose a storage type you want io1 or gp2.
    AllowedValues:
      - gp2
      - io1
  
  iops{{deploymentid}}:
    Type: Number
    Default: 1000
    MinValue: 1000
    Description: Give the number of I/O operations per second (IOPS) that the database provisions. Minimum value is 1000.
    
  maxallocatedstorage{{deploymentid}}:
    Description: Give the maximum allocated storage so that your database storage can autoscale if required.
    Default: 500
    Type: Number
    MinValue: 500
    MaxValue: 10000
    ConstraintDescription: must be between 500 and 10000 GiB.
  
  AllowMajorVersionUpgrade{{deploymentid}}: 
    Description: Allow Major Version Upgrade for AWS to perform the upgradation of MySQL platform automatically.If you want to allow major version upgrade select true otherwise select false. 
    Type: String
    Default: 'false'
    AllowedValues:
    - 'true'
    - 'false'
    
  AutoMinorVersionUpgrade{{deploymentid}}:
    Description: Allow Automatic Minor Version Upgrades for AWS to perform the upgradation of MySQL platform automatically. If you want to allow auto minor version upgrade select true otherwise select false.
    Type: String
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'
    
  MultiAvailabilityZone{{deploymentid}}:
    Description: Enable Multi Availability Zones? If you want to enable multi availability zone i.e. create a stand by RDS database instance for your database 
      select true otherwise false. 
    Type: String
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'
  
  Monitoringinterval{{deploymentid}}:
    Type: Number
    Default: 60
    AllowedValues:
      - 5
      - 10
      - 15 
      - 30 
      - 60
    Description: Select the monitoring interval to monitor your database. 

Conditions:
  storagetypegp2:
    Fn::Equals:
    - Ref: Storagetype{{deploymentid}}
    - gp2
  storagetypeio1: 
    Fn::Equals:
    - Ref: Storagetype{{deploymentid}}
    - io1
  
Resources:
  MysqlSecurityGroup{{deploymentid}}:
    Type: AWS::EC2::SecurityGroup
    Metadata:
      Description: Security Group without any ingress. Access is restricted only for the servers which associate this security group. 
    Properties:
      GroupName: 
        Fn::Sub: "${AWS::StackName}-MYSQL-SG"
      VpcId: 
        Ref: VPCID{{deploymentid}}
      GroupDescription: Enable MySql access via user defined port
            
  MysqlSubnetGroup{{deploymentid}}:
    Type: AWS::RDS::DBSubnetGroup
    Metadata:
      Description: An RDS Subnet Group is a collection of subnets that you can use to designate for your RDS database instance in a VPC. 
        It is always created using private subnets as per security best practices.
    Properties:
      DBSubnetGroupDescription: subnetgroup for mysql
      SubnetIds:
        - 
          Ref: PrivateSubnet1ID{{deploymentid}}
        - 
          Ref: PrivateSubnet2ID{{deploymentid}}
            
  MonitoringRole{{deploymentid}}:
    Type: AWS::IAM::Role
    Metadata:
      Description: Cloudwatch Enhance Monitoring is enabled using this role for your RDS database.
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "monitoring.rds.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
       
  MySQLDatabase{{deploymentid}}:
    Type: AWS::RDS::DBInstance
    Metadata:
      Description: Here a MYSQL DBInstance will be deployed. Which you can access using a mysql client from associated servers via security group.
    DeletionPolicy: Snapshot
    Properties:
      StorageType: 
        Ref: Storagetype{{deploymentid}}
      Iops: 
        Fn::If: 
        - storagetypeio1
        - Ref: iops{{deploymentid}}
        - Ref: "AWS::NoValue"
      MaxAllocatedStorage:
        Ref: maxallocatedstorage{{deploymentid}}
      MultiAZ:
        Ref: MultiAvailabilityZone{{deploymentid}}
      AllowMajorVersionUpgrade:
        Ref: AllowMajorVersionUpgrade{{deploymentid}}
      AutoMinorVersionUpgrade:
        Ref: AutoMinorVersionUpgrade{{deploymentid}}
      CopyTagsToSnapshot: true
      DeletionProtection: false
      DeleteAutomatedBackups: false
      PubliclyAccessible: false
      MonitoringRoleArn: 
        Fn::GetAtt: MonitoringRole{{deploymentid}}.Arn
      MonitoringInterval:
        Ref: Monitoringinterval{{deploymentid}}
      EnableCloudwatchLogsExports:
        - error
        - general
        - slowquery
      DBName:
        Ref: DBName{{deploymentid}}
      DBInstanceClass: 
        Ref: DBInstanceClass{{deploymentid}}
      AllocatedStorage:
        Fn::If: 
        - storagetypeio1
        - Ref: DBAllocatedStorage2{{deploymentid}}
        - Ref: DBAllocatedStorage1{{deploymentid}}
      Engine: 
        Ref: EngineName{{deploymentid}}
      EngineVersion:
        Ref: EngineVersion{{deploymentid}}
      MasterUsername: 
        Ref: DBUsername{{deploymentid}}
      MasterUserPassword: 
        Ref: DBPassword{{deploymentid}}
      VPCSecurityGroups:
        - Ref: MysqlSecurityGroup{{deploymentid}}
      DBSubnetGroupName:
        Ref: MysqlSubnetGroup{{deploymentid}}
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${AWS::StackName}-MYSQL-DBinstance"

Outputs:
  LogURL{{deploymentid}}: 
    Description: Click this link to get the error logs of your RDS database instance in cloudwatch.
    Value:
      Fn::Sub: 'https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logsV2:log-groups/log-group/$252Faws$252Frds$252Finstance$252F${MySQLDatabase{{deploymentid}}}$252Ferror/log-events'
    
  DbEndpoint{{deploymentid}}:
    Description: Hostname of the MySQL Instance.
    Value:
      Fn::GetAtt: MySQLDatabase{{deploymentid}}.Endpoint.Address
  
  DatabasePort{{deploymentid}}:
    Description: The port number on which MySQL is running.
    Value:
      Fn::GetAtt: MySQLDatabase{{deploymentid}}.Endpoint.Port
  
  Dbusername{{deploymentid}}:
    Description: Default username to connect to the Database.
    Value:
      Ref: DBUsername{{deploymentid}}
  
  Dbpassword{{deploymentid}}:
    Description: Default password to connect to the Database.
    Value:
      Ref: DBPassword{{deploymentid}}
        
  Dbname{{deploymentid}}:
    Description: Default database name to connect to the Database. 
    Value:
      Ref: DBName{{deploymentid}}
  
  DBIdentifier{{deploymentid}}:
    Description: Db instance identifier of RDS MySQL database instance.
    Value:
      Ref: MySQLDatabase{{deploymentid}}
  
  DbInstanceClass{{deploymentid}}:
    Description: DBinstance Type used to create MySQL Database Instance.
    Value:
      Ref: DBInstanceClass{{deploymentid}}
  
  StorageType{{deploymentid}}:
    Description: storage type used to create RDS Mysql db instance.
    Value: 
      Ref: Storagetype{{deploymentid}}
  
  Storagesize{{deploymentid}}:
    Description: Storage size for RDS MySQL db instance.
    Value:
      Fn::If: 
        - storagetypeio1
        - Ref: DBAllocatedStorage2{{deploymentid}}
        - Ref: DBAllocatedStorage1{{deploymentid}}
  
  Iops{{deploymentid}}:
    Description: Iops used if storage type is io1.
    Value:
      Ref: iops{{deploymentid}}
      
  SecurityGroupId{{deploymentid}}:
    Description: Security Group Id of MySQL which will give access to this database.
    Value:
      Ref: MysqlSecurityGroup{{deploymentid}}
  
  SubnetgrpId{{deploymentid}}:
    Description: Subnet group id of where the database resides.
    Value: 
      Ref: MysqlSubnetGroup{{deploymentid}}
  
  StackName{{deploymentid}}:
    Description: Cloudformation Stack Name of the database.
    Value: 
      Fn::Sub: "${AWS::StackName}"