---
- name: Step {{stepno}} - {{stepname}} - Executing
  block:
    - name:  Step {{stepno}} - {{stepname}}  - Task 1 - gitbranch -  Create Git Branches
      shell: |
        cd /tmp/{{apiname}}
        git checkout -b {{item}}
        git push origin {{item}}
      loop:
        "{{code.branches}}"
      register: gitbranch
  rescue:
    - name: Step {{stepno}} - {{stepname}} - Faiure Message Registering
      set_fact: 
        failedtask: "{{ansible_failed_task.name}}"
        failedmessage: "{{ansible_failed_result.msg}} -- {{ansible_failed_result.stderr}}"
    - name: 
      fail:
        msg:  Step {{stepno}} - {{stepname}}  is failed