---
- name: Step {{stepno}} - {{stepname}} - Executing
  block:
    - name: Step {{stepno}} - {{stepname}} - Task 1 - createlambdafolder - Create lambda folder
      file:
        path: "/tmp/{{apiname}}/{{function.name}}"
        state: directory
      register: createlambdafolder
    - name: Step {{stepno}} - {{stepname}} - Task 2 - copyrequirement.txt -  Copy the requirement file
      template:
        src: "requirement.txt"
        dest: "/tmp/{{apiname}}/{{function.name}}/requirement.txt"
        mode: 0755
    - name: Step {{stepno}} - {{stepname}} - Task 3 - copylambdactions-  Copy the lambda actions file
      template:
        src: "lambdaactions"
        dest: "/tmp/{{apiname}}/lambdaactions"
        mode: 0755
    - name: Step {{stepno}} - {{stepname}} - Task 4 - bootstrapcode-createapiactions Create API Actions
      shell: "/tmp/{{apiname}}/lambdaactions -n {{function.name}} -h {{function.Handler}}"
  rescue:
    - name: Step {{stepno}} - {{stepname}} - Faiure Message Registering
      set_fact: 
        failedtask: "{{ansible_failed_task.name}}"
        failedmessage: "{{ansible_failed_result.msg}} -- {{ansible_failed_result.stderr}}"
    - name: 
      fail:
        msg:  Step {{stepno}} - {{stepname}}  is failed
      