---
- name: Step {{stepno}} - {{stepname}} - Executing
  block:
    - name: Step {{stepno}} - {{stepname}} - Task 1 - lambda -  Create Lambda function
      include_tasks:
        file: createpackage.yaml
      loop:
        "{{lambdas}}"
      loop_control:
        loop_var: function
      register: function
    - name: Step {{stepno}} - {{stepname}}  - Task 2 - lambdaoutput - Register the outputs
      set_fact:
        update_output: "false"
        outputs: []
  rescue:
    - name: Step {{stepno}} - {{stepname}} - Faiure Message Registering
      set_fact: 
        failedtask: "{{ansible_failed_task.name}}"
        failedmessage: "{{ansible_failed_result.msg}} -- {{ansible_failed_result.stderr}}"
    - name: 
      fail:
        msg:  Step {{stepno}} - {{stepname}}  is failed

        