---
workflows:
  WorkflowId: wf-012345
  WorkflowName: productworkflow
  Environments:
  - Name: DYNAMODB
    parameters: default
    deploymentid: a012345
    dependentenv: []
  - Name: KEYPAIR
    parameters: default
    deploymentid: a012346
    dependentenv: []
  - Name: API-EC2-ASG-ALB-R53
    parameters: default
    deploymentid: a012347
    dependentenv:
    - name: DYNAMODB
      deploymentid: a012345
    - name: KEYPAIR
      deploymentid: a012346
